service:
  name: aws-nodejs-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-northeast-1
  profile: default

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
